[artf7713] Adding selenium test case for RMD and field mapping functionalities
2.29.0 fails with httpcore dependency error and seems to be known bug for the selenium 2.29.0 release.hence downgrading to 2.28.0 and verifying  the  selenium  tests are passing.

Updated httpclient to 4.2.3 version and selenium to 2.28.0


As selenium 2.28.0 uses httpclient 4.2.1 and the CCFMaster dragging in older version of  httpCient 4.1-alpha2 , maven end up by omitting 4.2.1 version of httpclient and thus causing the below error.

Hence upgraded the httpclient to 4.2.1 version and selenium to 2.29.0. 
Upgrading httpclient to newer version would not be an issue.since the 4.1 was added as a dependency for code coverage.

Selenium testing runs fine in local with the upgraded jars and Firefox12.Will promote to cu227 and check the sync happens and selenium runs successfully.

java.lang.NoSuchMethodError: org.apache.http.conn.scheme.Scheme.(Ljava/
lang/String;ILorg/apache/http/conn/scheme/SchemeSocketFactory;)V at
org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClientFactory.java:


git-svn-id: https://ctf.open.collab.net/svn/repos/ccf/branches/CCF%202.2@5558 6771e1e2-0f46-0410-b5d7-d846ff89f743